### ISSUE TITLE
Consider hosts

### ISSUE THREAD

**Issue by hobbldygoop** [popcorncolonel/TwitchBotDetector#10]
I've been curious about detecting viewbotters for a while and made some scripts for that and just saw your twitter and found it very interesting, so I checked a few of the streams you note as being viewbotted, and the first one with message `almost definitely has a false-viewer bot (~626 extra viewers of 654 total)` looked sketchy until I saw that he was being hosted by a big partnered streamer that had 700 people in his chat, so based on that I would assume there's a pretty good chance he's actually not viewbotting.

Aren't you getting a huge amount of false positives without including hosts in your tool?

There is a public API to see who's hosting a channel `https://tmi.twitch.tv/hosts?include_logins=1&target=[channel_id]` (needs an extra request to get the ID of a channel first).

**Comment by popcorncolonel** [comment]
Did not know about this endpoint, but thanks! Very helpful!

I'll try to do that this weekend.

**Comment by popcorncolonel** [comment]
Done!
