### ISSUE TITLE
Trying to get top games...

### ISSUE THREAD

**Issue by Cremaxx** [popcorncolonel/TwitchBotDetector#11]
What the fuck why is this happening?

trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...
trying to get top games...

**Comment by popcorncolonel** [comment]
Not sure exactly. Some exception is being thrown when checking the top games. It's not broken on my end -- try to walk through it in pdb or with some print statements to see the problem.
