### ISSUE TITLE
im new on python what is the problem of this?

### ISSUE THREAD

**Issue by Cremaxx** [popcorncolonel/TwitchBotDetector#4]
C:\Python27>python bdb.py
Traceback (most recent call last):
  File "bdb.py", line 1, in <module>
    from twitch_chatters import search_all_games, remove_offline
  File "C:\Python27\twitch_chatters.py", line 7, in <module>
    from get_exceptions import get_exceptions
ImportError: No module named get_exceptions

C:\Python27>python bdb.py
Traceback (most recent call last):
  File "bdb.py", line 1, in <module>
    from twitch_chatters import search_all_games, remove_offline
  File "C:\Python27\twitch_chatters.py", line 6, in <module>
    from twitch_viewers import user_viewers, removeNonAscii, user_total_views
  File "C:\Python27\twitch_viewers.py", line 7, in <module>
    from get_passwords import CLIENT_ID
ImportError: No module named get_passwords

**Comment by popcorncolonel** [comment]
You have to look at the twitch_passwords.py.example file and write your own passwords.py file based on your own twitch account info - I didn't want to include botdetectorbot's twitch username and password when I created the github repo.

**Comment by Cremaxx** [comment]
okay :D i try it if i have problems can you help me :D? im a fan of your bot :D
