### ISSUE TITLE
Hey got a Twitter problem :C

### ISSUE THREAD

**Issue by Cremaxx** [popcorncolonel/TwitchBotDetector#7]
root@ggba:/home/twitchDetector# clear
root@ggba:/home/twitchDetector# python bdb.py
Traceback (most recent call last):
  File "bdb.py", line 1, in <module>
    from twitch_chatters import search_all_games, remove_offline
  File "/home/twitchDetector/twitch_chatters.py", line 24, in <module>
    import handle_twitter
  File "/home/twitchDetector/handle_twitter.py", line 27, in <module>
    api = twitter.Api(APP_KEY, APP_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET)
AttributeError: 'module' object has no attribute 'Api'
root@ggba:/home/twitchDetector#

, OAUTH_TOKEN_SECRET)
AttributeError: 'module' object has no attribute 'Api'

Can you say me how to fix it

**Comment by popcorncolonel** [comment]
Try pip installing python-twitter rather than "pip install twitter"
  
  
  

  
  
>

**Comment by Cremaxx** [comment]
root@ggba:/home/twitchDetector# pip installing python-twitter
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
root@ggba:/home/twitchDetector#

this happens

**Comment by popcorncolonel** [comment]
"pip install python-twitter". If you still keep getting the same error, try googling that error message. You might have to update/reinstall pip.   
  
  
  

  
  
>

**Comment by Cremaxx** [comment]
okay

**Comment by Cremaxx** [comment]
okay i fixed it BUT the python script is slower on my vps on my pc is it faster? (my vps has better connection)

**Comment by Cremaxx** [comment]
Hosted by NFOrce Entertainment B.V. (Amsterdam) [1.75 km]: 49.738 ms
Testing download speed........................................
Download: 485.48 Mbit/s
Testing upload speed..................................................
Upload: 50.44 Mbit/s

**Comment by Cremaxx** [comment]
is this script only fast on Windows not linux?

**Comment by popcorncolonel** [comment]
I've run it on Windows, Mac, and Linux, and the performance has been equal on all. The issue is elsewhere. It's currently running on my Linux server, which hasn't had any issues.   
  
  

  
  
>

**Comment by Cremaxx** [comment]
and you dont know what the problem ist? :D

**Comment by Cremaxx** [comment]
is*

**Comment by popcorncolonel** [comment]
Nope :) something on your end
  
  
  

  
  
>
