### ISSUE TITLE
Add logic to prevent false positives.

### ISSUE THREAD

**Issue by Stubby** [popcorncolonel/TwitchBotDetector#8]
There are several available endpoints to determine if you might be alerting on a false positive.  I recommend adding a check for https://api.twitch.tv/kraken/streams/featured as the returned data represents streams that will see higher traffic than normal and including those in a list of possible violators reduces the credibility of the data returned.

Rather than putting the onus on those using this library in their own code this should be built in as the data is readily available.  A new class perhaps that acts as a filter to ensure that only the best and most reliable data is returned.

**Comment by popcorncolonel** [comment]
Thanks for mentioning this! If you scrape around you'll see that I was already pseudo checking for featured streams, but that code was probably written before that endpoint was exposed (it just queries www.twitch.tv and doesn't add streams if they're listed there). That endpoint would definitely be more reliable though. I'll look into adding it soon.

**Comment by Stubby** [comment]
Right, however polling twitch.tv will present issues as if they ever load content with JS you won't necessarily get reliable information.  The endpoint is actually carried over from the Justin.tv blob API, however it doesn't just provide front page, it provides anything that's currently featured live or not so it gives you a really good filter to check against.

**Comment by popcorncolonel** [comment]
Totally. I'll look into it.

**Comment by Stubby** [comment]
No worries,  I had a friend who was spotlighted this week that got tagged by Twitter bots who I suspect probably based their code off of this (if not, hey improved code!) and it really gave a great thing for him a very sour note.

Either way if it helps make your source that much better I'm happy to help.

**Comment by popcorncolonel** [comment]
https://github.com/popcorncolonel/TwitchBotDetector/commit/3f939a10a6bd556d3df94821757e997f27092097
